apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
       app: frontend
    spec:
      containers:
        - name: frontend-container
          image: azuredocs/azure-vote-front:ed1d16d1b2bc892e167177d6869b647bad30ab9f
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    srvce: frontend-srvce
  name: frontend-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: frontend-port-name
    port: 80
    protocol: TCP
  selector:
   app: frontend

    
