apiVersion: apps/v1
kind: Deployment
metadata:
  name: collegepj-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collegepj-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: collegepj-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-cl-front
        image: mcr.microsoft.com/azuredocs/azure-vote-front:14325c72c6186cc89fef0ac66cc6d0363148ed43
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: collegepj-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: collegepj-front
