
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main
name: SonarQube Scan
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@master
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
  
    - name: Build Client Docker Image
      working-directory: ./frontend
        # Build image with tag ashiq22/productivity-app:client
      run: |
         docker build -t ashiq22/productivity-app:client-${{github.run_number}}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker images to Docker Hub
    - name: Push Docker Images to Docker Hub
      run: |
        docker push ashiq22/productivity-app:client-${{github.run_number}}

