
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main
name: SonarQube Scan
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@master
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
   
    - name: Build client Docker Image
      working-directory: ./frontend
      
      run: |
         docker build . --file Dockerfile -t ashiq22/new:client-${{github.run_number}}
         
    - name: Build server Docker Image
      working-directory: ./backend
       
      run: |
         docker build . --file Dockerfile -t ashiq22/new:server-${{github.run_number}}

    - name: Azure Login
      uses: azure/login@14a755a4e2fd6dff25794233def4f2cf3f866955
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: myproject-082023
        resource-group: myProjectRG

        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker images to Docker Hub
    - name: Push Docker Images to Docker Hub
      run: |
        docker push ashiq22/new:server-${{github.run_number}}
        docker push ashiq22/new:client-${{github.run_number}}
